### ISSUE TITLE
DNS::Unbound fails install where Net::DNS::Resolver::Unbound succeeds

### ISSUE THREAD

**Issue by rwfranks** [FGasper/p5-DNS-Unbound#3]
````
[rwf@pandora DNS-Unbound-0.28]$ perl Makefile.PL 
Your C compiler appears to be: gcc
Hmm. You don’t seem to have ExtUtils::PkgConfig.
I’ll try running `pkg-config` directly …
Cool. It looks like pkg-config works.
CFLAGS: [-I/usr/include/python3.10 ]
LDFLAGS: [-lunbound ]
Checking: sanity … 
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_is_sctp@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
  sanity: no
libunbound didn’t compile! (CHILD_ERROR=256) at Makefile.PL line 159.

```

**Comment by FGasper** [comment]
@rwfranks Thanks for the report.

Is this the default dnf-provided libunbound?

**Comment by FGasper** [comment]
This is what I see with a fresh Fedora 35 install against the repository:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/844867/156698215-0580d804-e7b0-48a3-812f-98118382a633.png">

`cpanm` also installs the distribution just fine.

**Comment by rwfranks** [comment]
> @rwfranks Thanks for the report.
> 
> Is this the default dnf-provided libunbound?

Yes
1.13.2

**Comment by FGasper** [comment]
@rwfranks So, it works for me, both from CPAN and from the repo.

Is it possible that your machine is misconfigured?

**Comment by rwfranks** [comment]
> @rwfranks So, it works for me, both from CPAN and from the repo.
> 
> Is it possible that your machine is misconfigured?

Extremely unlikely. Unbound works fine for me.

**Comment by FGasper** [comment]
I installed Fedora 35 onto a fresh VM and, with dnf’s perl and unbound, built the module both with the repo and with CPAN. Thus, the problem doesn’t appear intrinsic to the combination of this OS and the module.

Can you offer any further insight as to what may be causing your error? Are you able to link other C programs against your libunbound and run them?

**Comment by FGasper** [comment]
Of note: CPAN Testers has [a working run from Fedora Core 34](http://www.cpantesters.org/cpan/report/6e01ddec-99f7-11ec-8e10-45381f24ea8f).

**Comment by rwfranks** [comment]
> I installed Fedora 35 onto a fresh VM and, with dnf’s perl and unbound, built the module both with the repo and with CPAN. Thus, the problem doesn’t appear intrinsic to the combination of this OS and the module.
> 
> Can you offer any further insight as to what may be causing your error? Are you able to link other C programs against your libunbound and run them?

Yes.
As I was getting no joy from DNS::Unbound, I wrote Net::DNS::Resolver::Unbound instead, which (a) works, (b) is fully integrated with Net::DNS, (c) is less complicated and (d) has none of the unnecessary dependencies.

**Comment by FGasper** [comment]
Good to know you’ve found a solution for your use case. I’ll link to it whenever I next update DNS::Unbound.

I’m respectfully going to assume this is, in fact, a peculiarity of your setup. We’ve built DNS::Unbound and used it in production to query millions of domains for some time now. CPAN Testers boxes run it. In my own testing, Fedora 35 compiled it out-of-the-box. I’m not sure what more I can do for you at this juncture.

If you have further details as to how I might reproduce your setup, feel free to reopen this.

Thanks!

**Comment by FGasper** [comment]
@rwfranks One thing: would you please retry the build with this line in DNS::Unbound’s Makeefile.PL uncommented, then paste the result here?
```
    # print "Compiling test program: `$cmd`\n";
```
Thanks!

**Comment by rwfranks** [comment]
> @rwfranks One thing: would you please retry the build with this line in DNS::Unbound’s Makeefile.PL uncommented, then paste the result here?
> 
> ```
>     # print "Compiling test program: `$cmd`\n";

Compiling test program: `gcc -I/usr/include/python3.10  /tmp/D4duCgBC8w/check.c -lunbound  -o /tmp/D4duCgBC8w/check`

 ```

**Comment by FGasper** [comment]
Yup, that’s the same as what I have.

So the question is why this program (`sanity.c`):
```
#include <unbound.h>

int main() {
    struct ub_result myresult;
    return 0;
}
```
… compiled with `gcc -I/usr/include/python3.10 sanity.c -lunbound` fails for you while it passes in my FC 35 VM.

Can you also run these commands, please?
```
rpm -qa | grep unbound
rpm -qa | grep ssl
objdump -t /usr/lib64/libssl.so.1.1 | grep dgram_sctp
```

**Comment by rwfranks** [comment]
> rpm -qa | grep unbound
> rpm -qa | grep ssl
> objdump -t /usr/lib64/libssl.so.1.1 | grep dgram_sctp

```

python3-unbound-1.13.2-1.fc35.x86_64
unbound-libs-1.13.2-1.fc35.x86_64
unbound-1.13.2-1.fc35.x86_64
unbound-devel-1.13.2-1.fc35.x86_64


openssl-pkcs11-0.4.11-4.fc35.x86_64
openssl-libs-1.1.1l-2.fc35.x86_64
apr-util-openssl-1.6.1-17.fc35.x86_64
xmlsec1-openssl-1.2.29-4.fc35.x86_64
openssl-1.1.1l-2.fc35.x86_64
openssl-devel-1.1.1l-2.fc35.x86_64
openssl-pkcs11-0.4.11-4.fc35.i686
openssl-libs-1.1.1l-2.fc35.i686


0000000000000000       F *UND*  0000000000000000 BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0
0000000000000000       F *UND*  0000000000000000 BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0

```

**Comment by FGasper** [comment]
OK, now could you please:
1) Confirm that `sanity.c` fails to compile/link/run when linked only with `-lunbound`.
2) Try `gcc -I/usr/include/python3.10 sanity.c -lcrypto -lssl -lunbound`, and see if that works better.

**Comment by FGasper** [comment]
Also:
1) Please paste the output of a build of Net::DNS::Resolver::Unbound.
2) `objdump -t /lib/libcrypto.so.1.1 | grep BIO_dgram_sctp
3) `ldd /usr/lib64/libssl.so.1.1`

**Comment by FGasper** [comment]
Also try this in Makefile.PL:
```
my $cmd = "$ccpath $cflags $cpath -o $progpath $ldflags";
```
(i.e., $ldflags at the end)

**Comment by rwfranks** [comment]
>     1. Confirm that `sanity.c` fails to compile/link/run when linked only with `-lunbound`
```
Compiling test program: `gcc /tmp/Wz0JaHixO7/check.c -lunbound -o /tmp/Wz0JaHixO7/check`
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_is_sctp@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
```
> 
>     2. Try `gcc -I/usr/include/python3.10 sanity.c -lcrypto -lssl -lunbound`, and see if that works better.
```
Compiling test program: `gcc -I/usr/include/python3.10  /tmp/Wz0JaHixO7/check.c -lcrypto -lssl -lunbound -o /tmp/Wz0JaHixO7/check`
  sanity: yes
Checking: ub_version() … 
Compiling test program: `gcc /tmp/Bb4avOheP6/check.c -lunbound -o /tmp/Bb4avOheP6/check`
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_is_sctp@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
Compiling test program: `gcc -I/usr/include/python3.10  /tmp/Bb4avOheP6/check.c -lcrypto -lssl -lunbound -o /tmp/Bb4avOheP6/check`
  ub_version(): yes
Checking: ub_result.ttl … 
Compiling test program: `gcc /tmp/q56LWY31NX/check.c -lunbound -o /tmp/q56LWY31NX/check`
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_is_sctp@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
Compiling test program: `gcc -I/usr/include/python3.10  /tmp/q56LWY31NX/check.c -lcrypto -lssl -lunbound -o /tmp/q56LWY31NX/check`
  ub_result.ttl: yes
Checking: UB_* constants … 
Compiling test program: `gcc /tmp/B3rF5WPZo7/check.c -lunbound -o /tmp/B3rF5WPZo7/check`
/tmp/B3rF5WPZo7/check.c: In function ‘main’:
/tmp/B3rF5WPZo7/check.c:3:14: error: ‘UB_NOERROR’ undeclared (first use in this function)
    3 |    int foo = UB_NOERROR;
      |              ^~~~~~~~~~
/tmp/B3rF5WPZo7/check.c:3:14: note: each undeclared identifier is reported only once for each function it appears in
Compiling test program: `gcc -I/usr/include/python3.10  /tmp/B3rF5WPZo7/check.c -lcrypto -lssl -lunbound -o /tmp/B3rF5WPZo7/check`
/tmp/B3rF5WPZo7/check.c: In function ‘main’:
/tmp/B3rF5WPZo7/check.c:3:14: error: ‘UB_NOERROR’ undeclared (first use in this function)
    3 |    int foo = UB_NOERROR;
      |              ^~~~~~~~~~
/tmp/B3rF5WPZo7/check.c:3:14: note: each undeclared identifier is reported only once for each function it appears in
  UB_* constants: no
```

**Comment by rwfranks** [comment]
> 
>     1. Please paste the output of a build of Net::DNS::Resolver::Unbound.
```
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Net::DNS::Resolver::Unbound
Writing MYMETA.yml and MYMETA.json
cp lib/Net/DNS/Resolver/Unbound.pm blib/lib/Net/DNS/Resolver/Unbound.pm
Running Mkbootstrap for Unbound ()
chmod 644 "Unbound.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Unbound.bs blib/arch/auto/Net/DNS/Resolver/Unbound/Unbound.bs 644
"/usr/bin/perl" "/usr/share/perl5/vendor_perl/ExtUtils/xsubpp"  -typemap '/usr/share/perl5/ExtUtils/typemap' -typemap '/tmp/Net-DNS-Resolver-Unbound-1.08/typemap'  Unbound.xs > Unbound.xsc
mv Unbound.xsc Unbound.c
gcc -c  -I/usr/include/python3.10  -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g   -DVERSION=\"1.08\" -DXS_VERSION=\"1.08\" -fPIC "-I/usr/lib64/perl5/CORE"   Unbound.c
rm -f blib/arch/auto/Net/DNS/Resolver/Unbound/Unbound.so
gcc  -lpthread -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -L/usr/local/lib -fstack-protector-strong  Unbound.o  -o blib/arch/auto/Net/DNS/Resolver/Unbound/Unbound.so  \
   -lunbound -lperl   \
  
chmod 755 blib/arch/auto/Net/DNS/Resolver/Unbound/Unbound.so
```
> 
>     2. `objdump -t /lib/libcrypto.so.1.1 | grep BIO_dgram_sctp
```
0006911c l       .text	00000000 .hidden .annobin_BIO_dgram_sctp_notification_cb.start
0006914c l       .text	00000000 .hidden .annobin_BIO_dgram_sctp_notification_cb.end
0006914c l       .text	00000000 .hidden .annobin_BIO_dgram_sctp_wait_for_dry.start
000694d2 l       .text	00000000 .hidden .annobin_BIO_dgram_sctp_wait_for_dry.end
000694d2 l       .text	00000000 .hidden .annobin_BIO_dgram_sctp_msg_waiting.start
0006968d l       .text	00000000 .hidden .annobin_BIO_dgram_sctp_msg_waiting.end
00069120 g     F .text	0000002c BIO_dgram_sctp_notification_cb
00069150 g     F .text	00000382 BIO_dgram_sctp_wait_for_dry
000694e0 g     F .text	000001ad BIO_dgram_sctp_msg_waiting
```
> 
>     3. `ldd /usr/lib64/libssl.so.1.1`
```
	linux-vdso.so.1 (0x00007ffd8af76000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fe66a5bf000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe66a3b5000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fe66a39b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe66a961000)
```

**Comment by FGasper** [comment]
I’ll look at these a bit later, but FYI, I’ve added a CI run against Fedora 35:
https://github.com/FGasper/p5-DNS-Unbound/runs/5434915547?check_suite_focus=true

As you can see, it succeeds.

I’m ok to keep helping you, but I’m going to rename this issue since it doesn’t seem relevant to FC35 per se.

**Comment by FGasper** [comment]
```
Compiling test program: `gcc -I/usr/include/python3.10  /tmp/Wz0JaHixO7/check.c -lcrypto -lssl -lunbound -o /tmp/Wz0JaHixO7/check`
  sanity: yes
```
OK. So this indicates that for whatever reason your linker either doesn’t bring in `-lcrypto -lssl`, or it thinks it needs those libraries when it actually doesn’t.

Of note: this breakage on your system happens because of DNS::Unbound’s feature detection, which I added to maximize compatibility with older systems (esp. CPAN Testers). You could, if you just want DNS::Unbound to work, simply forgo that and manually set the various `-D` options in Makefile.PL as per your system’s libunbound capabilities.

**Comment by FGasper** [comment]
Try making this change:
```
-    my $cmd = "$ccpath $cflags $cpath -o $progpath $ldflags";
+    my $cmd = "$ccpath $Config{'ccflags'} $cflags $cpath -o $progpath $Config{ccdlflags} $ldflags";
```
… then run Makefile.PL. Does that fix it?

**Comment by rwfranks** [comment]
> Try making this change:
> ```
> -    my $cmd = "$ccpath $cflags $cpath -o $progpath $ldflags";
> +    my $cmd = "$ccpath $Config{'ccflags'} $cflags $cpath -o $progpath $Config{ccdlflags} $ldflags";
> ```
> … then run Makefile.PL. Does that fix it?
Yes, but still has undefined symbols and a lot of noise.

```
Your C compiler appears to be: gcc
Hmm. You don’t seem to have ExtUtils::PkgConfig.
I’ll try running `pkg-config` directly …
Cool. It looks like pkg-config works.
CFLAGS: [-I/usr/include/python3.10 ]
LDFLAGS: [-lunbound ]
Checking: sanity … 
/tmp/IvfHDhGZxE/check.c: In function ‘main’:
/tmp/IvfHDhGZxE/check.c:3:21: warning: unused variable ‘myresult’ [-Wunused-variable]
    3 |    struct ub_result myresult;
      |                     ^~~~~~~~
  sanity: yes
Checking: ub_version() … 
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_is_sctp@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
  ub_version(): no
Checking: ub_result.ttl … 
/tmp/scI1UMwdcf/check.c: In function ‘main’:
/tmp/scI1UMwdcf/check.c:3:21: warning: variable ‘myresult’ set but not used [-Wunused-but-set-variable]
    3 |    struct ub_result myresult;
      |                     ^~~~~~~~
  ub_result.ttl: yes
Checking: UB_* constants … 
/tmp/eETSJCC0AI/check.c: In function ‘main’:
/tmp/eETSJCC0AI/check.c:3:14: error: ‘UB_NOERROR’ undeclared (first use in this function)
    3 |    int foo = UB_NOERROR;
      |              ^~~~~~~~~~
/tmp/eETSJCC0AI/check.c:3:14: note: each undeclared identifier is reported only once for each function it appears in
/tmp/eETSJCC0AI/check.c:3:8: warning: unused variable ‘foo’ [-Wunused-variable]
    3 |    int foo = UB_NOERROR;
      |        ^~~
  UB_* constants: no
Checking: ub_result.why_bogus … 
/tmp/0CAByR9hUa/check.c: In function ‘main’:
/tmp/0CAByR9hUa/check.c:3:21: warning: variable ‘myresult’ set but not used [-Wunused-but-set-variable]
    3 |    struct ub_result myresult;
      |                     ^~~~~~~~
  ub_result.why_bogus: yes
Checking: ub_cancel() … 
/tmp/BBf5tmTQ7x/check.c: In function ‘main’:
/tmp/BBf5tmTQ7x/check.c:4:4: warning: ‘myctx’ is used uninitialized [-Wuninitialized]
    4 |    ub_cancel(myctx, 0);
      |    ^~~~~~~~~~~~~~~~~~~
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_is_sctp@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
  ub_cancel(): no
Checking: ub_ctx_add_ta_autr() … 
/tmp/_xie27mDeO/check.c: In function ‘main’:
/tmp/_xie27mDeO/check.c:4:4: warning: ‘myctx’ is used uninitialized [-Wuninitialized]
    4 |    ub_ctx_add_ta_autr(myctx, "/faux");
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_msg_waiting@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_is_sctp@OPENSSL_1_1_0'
/usr/bin/ld: /usr/lib64/libssl.so.1.1: undefined reference to `BIO_dgram_sctp_wait_for_dry@OPENSSL_1_1_0'
collect2: error: ld returned 1 exit status
  ub_ctx_add_ta_autr(): no
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for DNS::Unbound
Writing MYMETA.yml and MYMETA.json
```

**Comment by FGasper** [comment]
Some (not all) of the noise is a product of the feature detection. Regardless, that’s a separate concern.

The fact that _some_, not all, of the undef’d-symbol errors are fixed here is interesting.

If you can suss out how to reproduce this issue I’d love to have it in CI.

**Comment by FGasper** [comment]
Noise fixed: https://github.com/FGasper/p5-DNS-Unbound/runs/5454083469

**Comment by FGasper** [comment]
@rwfranks: Would you be able to grab HEAD from master on this repo and retry, please?

**Comment by rwfranks** [comment]
> @rwfranks: Would you be able to grab HEAD from master on this repo and retry, please?

Yes, that stops the noise but does not do anything about undefined symbols or missing references.
If ou want more, I suggest you set up your own Fedora35.

**Comment by FGasper** [comment]
@rwfranks 

> If ou want more, I suggest you set up your own Fedora35.

That’s the very first thing I did, in fact. Please reread the thread for multiple examples, including links to CI runs against Fedora 35’s official Docker image.

-----
> I wrote Net::DNS::Resolver::Unbound instead, which (a) works, (b) is fully integrated with Net::DNS, (c) is less complicated and (d) has none of the unnecessary dependencies.

Your module, by inheriting Resolver.pm’s dependencies, is actually much heavier than DNS::Unbound. It also doesn’t integrate with event loops or throw machine-parsable errors. These would make it a non-starter for us, though it’s good for Perl in general that there are now two supported Unbound bindings.
